# Generated by Django 3.2.23 on 2023-12-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_additional_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
