---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test amd Lint # Job name
    runs-on: ubuntu-20.04 # GitHub-hosted Ubuntu 20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Docker Hub login action
        with:
          username: ${{ secrets.DOCKERHUB_USER }} # Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub access token
      - name: Checkout
        uses: actions/checkout@v2 # Checkout the repository
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"